version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    expose:
      - 8000
    environment:
      - ALLOWED_HOSTS=${DOMAIN},127.0.0.1,localhost
  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
      - ./nginx/cert:/etc/nginx/cert:ro
    ports:
      - ${HTTPS_MAPPING}
      - ${HTTP_MAPPING}
    depends_on:
      - app

volumes:
  static_data: