version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - /usr/local/bin/geckodriver:/usr/local/bin/geckodriver
    command: sh -c "python manage.py test"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=dev.ivanne.de,127.0.0.1,localhost