version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    expose:
      - 8000
    environment:
      - ALLOWED_HOSTS=dev.ivanne.de,127.0.0.1,localhost

  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
      - ./nginx/dev.ivanne.de:/etc/nginx/dev.ivanne.de:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - app

volumes:
  static_data: