version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ALLOWED_HOSTS=box.ivanne.de,127.0.0.1,localhost

  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:8080
    depends_on:
      - app

volumes:
  static_data: